id: I23341B4B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T00:11:28+00:00'
last_modified: '2022-06-08T17:52:23.747209+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017331
  title: པད་གླིང་ལོ་རྒྱུས་དྲང་གཏམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4C14:
      image_group_id: I00EGS1017333
      title: Volume 1 of
      total_pages: 204
      order: 1
      base_file: 4C14.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
