id: P008021
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00EGS1017331
  title: པད་གླིང་ལོ་རྒྱུས་དྲང་གཏམ
  author: ''
  volumes:
    b4818dab30ce45c3b64858b3a857317f:
      image_group_id: I00EGS1017333
      title: Volume 1 of
      volume_number: 1
      total_pages: 204
      base_file: v001.txt
