id: P008021
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1017331
  title: པད་གླིང་ལོ་རྒྱུས་དྲང་གཏམ
  author: ''
  volumes:
    ceae2d2493024422ad1c5b24c394cf07:
      image_group_id: I00EGS1017333
      title: ''
      volume_number: 1
      total_pages: 204
ebook_metadata:
  title: པད་གླིང་ལོ་རྒྱུས་དྲང་གཏམ
  author: ''
  sku: P008021
  cover: cover.jpg
  layers:
  - pagination
